audio:
  default_file: Haunted_Gallery_Greeting.wav
  soundfiles_dir: SoundFiles
  volume: 100
hardware:
  gpio:
    led_eyes: 15
    motor_head_in1: 4
    motor_head_in2: 14
    motor_mouth_in1: 23
    motor_mouth_in2: 22
    motor_torso_in1: 17
    motor_torso_in2: 18
    sensor_port_left: 9
    sensor_port_right: 25
idle_behavior:
  duration_seconds: 15
  enabled: false
  interval_seconds: 240
logging:
  backup_count: 5
  file: logs/ghosthost.log
  level: INFO
  max_size: 10MB
motors:
  head_torso_duration: 0
  mouth_close_delay: 0.05
  mouth_open_duration: 0.1
network:
  ap_mode:
    ip_address: 192.168.4.1
    password: ''
    ssid: ghosthost
    subnet: 192.168.4.0/24
    timeout: 300
  fallback_ssid: ''
sensors:
  cooldown_period: 15
  debounce_time: 0.2
web:
  debug: false
  host: 0.0.0.0
  port: 8000
